In [1]:
import numpy as np
np.zeros((2,2))
np.ones((2,3))
aid = np.arange(2, 9, 2)
print(aid)
zeros, ones = np.zeros(2), np.ones(2)
print(zeros, ones)
np.array([1,2,3], dtype = np.int16 )

[2 4 6 8]
[0. 0.] [1. 1.]


array([1, 2, 3], dtype=int16)

In [3]:
import numpy as np

#The shape vs size of an array
a2d = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print('The total number of elements in the array is:',a2d.size)

rows, columns = a2d.shape
print(a2d.shape)
print('The number of rows is:',rows,'the number of columns is:',columns)

The total number of elements in the array is: 12
(3, 4)
The number of rows is: 3 the number of columns is: 4


In [4]:
a3 = np.zeros(3)
a3

array([0., 0., 0.])

In [6]:
a3 = np.zeros((3), dtype=int)
a3

array([0, 0, 0])

In [9]:
a4 = np.zeros((4, 3))
a4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
a1 = np.array([1,2,3,4,5])
a1 

array([1, 2, 3, 4, 5])

In [13]:
a4 = np.array([[1,2,3], [4,5,6], [7, 8, 9]])
a4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a1 = np.arange(20)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
a1[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:

a1[18::-1]

array([18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,
        1,  0])

In [2]:
import numpy as np
a2 = np.array([[4,5,32,2], [2,34,23,12],[12,32,7,99]])
a2

array([[ 4,  5, 32,  2],
       [ 2, 34, 23, 12],
       [12, 32,  7, 99]])

In [3]:
a2[:2, :3]

array([[ 4,  5, 32],
       [ 2, 34, 23]])

In [4]:
a2[:,:1]

array([[ 4],
       [ 2],
       [12]])

In [5]:
a2[:3, ::2]

array([[ 4, 32],
       [ 2, 23],
       [12,  7]])

In [8]:
print('orginal a2: \n', a2)
print('reverted a2: \n', a2[::-1, ::-1])

orginal a2: 
 [[ 4  5 32  2]
 [ 2 34 23 12]
 [12 32  7 99]]
reverted a2: 
 [[99  7 32 12]
 [12 23 34  2]
 [ 2 32  5  4]]


In [17]:
a1d = np.arange(0, 12)
print('a1d before reshape: \n', a1d)
a1d = a1d.reshape(3,4)
print('a1d after the reshape: \n', a1d)
a2d = np.arange(4, 16).reshape(3, 4)
print('')
print(a2d)

a1d before reshape: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
a1d after the reshape: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [41]:
a1 = np.array([1, 2, 3])
a2 = np.array([2, 5, 7])
a3 = np.array([5, 9, 14])
a4 = a1 + a2 + a3
a5 = np.concatenate([a1, a2, a3])
print(a4)
print('')
print(a5)

[ 8 16 24]

[ 1  2  3  2  5  7  5  9 14]


In [42]:
matrix = np.array(((1,2,3), (4, 5, 6)))
print(matrix)
matrix2 = np.array([[7,8,9], [432, 43243, 4324]])
print(matrix2)
matrix3 = np.array([[3,45,34], [32, 432, 12]])
print(matrix3)
print('')
matrix_conbine = np.concatenate([matrix, matrix2, matrix3], axis = 1)
print(matrix_conbine)

[[1 2 3]
 [4 5 6]]
[[    7     8     9]
 [  432 43243  4324]]
[[  3  45  34]
 [ 32 432  12]]

[[    1     2     3     7     8     9     3    45    34]
 [    4     5     6   432 43243  4324    32   432    12]]


In [46]:
v1 =np.array([[1, 2],[3,4]])
matrix = np.array([[4, 5, 6],[7, 8, 9]])
v2 = np.concatenate([v1, matrix], axis = 1)
print(v2)

[[1 2 4 5 6]
 [3 4 7 8 9]]


In [49]:
a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[5, 6], [7, 8]])

result = np.hstack((a1, a2))
result2 = np.concatenate([a1, a2], axis = 1)
print(result)
print('')
print(result2)

[[1 2 5 6]
 [3 4 7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [57]:
result = np.array([1,2,3,4,5,6,7,8])
s1, s2, s3, s4 =np.split(result, [2,5,7])
print(s1)
print(s2)
print(s3)
print(s4)
print(np.split(result, [1, 3, 6]))

[1 2]
[3 4 5]
[6 7]
[8]
[array([1]), array([2, 3]), array([4, 5, 6]), array([7, 8])]


In [73]:
matrix = np.arange(36).reshape([6,6])
print(matrix)
print('--')
m1, m2, m3 =np.hsplit(matrix, 3)
print(m1)
print('')
print(m2)
print('')
print(m3)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
--
[[ 0  1]
 [ 6  7]
 [12 13]
 [18 19]
 [24 25]
 [30 31]]

[[ 2  3]
 [ 8  9]
 [14 15]
 [20 21]
 [26 27]
 [32 33]]

[[ 4  5]
 [10 11]
 [16 17]
 [22 23]
 [28 29]
 [34 35]]
